package com.mycompany.bus_management.domain;
// Generated Jul 25, 2018 2:36:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Booking generated by hbm2java
 */
@Entity
@Table(name="booking"
    ,catalog="bus_management"
)
public class Booking  implements java.io.Serializable {


     private Integer bookId;
     private BusInfo busInfo;
     private BusSchedule busSchedule;
     private Passenger passenger;
     private RouteCounter routeCounter;
     private Date bookDate;
     private String bookStatus;
     private Integer totalSeat;
     private Set<BookingSeat> bookingSeats = new HashSet<BookingSeat>(0);

    public Booking() {
    }

    public Booking(BusInfo busInfo, BusSchedule busSchedule, Passenger passenger, RouteCounter routeCounter, Date bookDate, String bookStatus, Integer totalSeat, Set<BookingSeat> bookingSeats) {
       this.busInfo = busInfo;
       this.busSchedule = busSchedule;
       this.passenger = passenger;
       this.routeCounter = routeCounter;
       this.bookDate = bookDate;
       this.bookStatus = bookStatus;
       this.totalSeat = totalSeat;
       this.bookingSeats = bookingSeats;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="book_id", unique=true, nullable=false)
    public Integer getBookId() {
        return this.bookId;
    }
    
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bus_id")
    public BusInfo getBusInfo() {
        return this.busInfo;
    }
    
    public void setBusInfo(BusInfo busInfo) {
        this.busInfo = busInfo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="schedule_id")
    public BusSchedule getBusSchedule() {
        return this.busSchedule;
    }
    
    public void setBusSchedule(BusSchedule busSchedule) {
        this.busSchedule = busSchedule;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pass_id")
    public Passenger getPassenger() {
        return this.passenger;
    }
    
    public void setPassenger(Passenger passenger) {
        this.passenger = passenger;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="counter_id")
    public RouteCounter getRouteCounter() {
        return this.routeCounter;
    }
    
    public void setRouteCounter(RouteCounter routeCounter) {
        this.routeCounter = routeCounter;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="book_date", length=10)
    public Date getBookDate() {
        return this.bookDate;
    }
    
    public void setBookDate(Date bookDate) {
        this.bookDate = bookDate;
    }

    
    @Column(name="book_status", length=45)
    public String getBookStatus() {
        return this.bookStatus;
    }
    
    public void setBookStatus(String bookStatus) {
        this.bookStatus = bookStatus;
    }

    
    @Column(name="total_seat")
    public Integer getTotalSeat() {
        return this.totalSeat;
    }
    
    public void setTotalSeat(Integer totalSeat) {
        this.totalSeat = totalSeat;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="booking")
    public Set<BookingSeat> getBookingSeats() {
        return this.bookingSeats;
    }
    
    public void setBookingSeats(Set<BookingSeat> bookingSeats) {
        this.bookingSeats = bookingSeats;
    }




}


