package com.mycompany.bus_management.domain;
// Generated Jul 25, 2018 2:36:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BookingSeat generated by hbm2java
 */
@Entity
@Table(name="booking_seat"
    ,catalog="bus_management"
)
public class BookingSeat  implements java.io.Serializable {


     private Integer bookSeatId;
     private Booking booking;
     private BusInfo busInfo;
     private Passenger passenger;
     private String seatNo;
     private Date bookDate;

    public BookingSeat() {
    }

    public BookingSeat(Booking booking, BusInfo busInfo, Passenger passenger, String seatNo, Date bookDate) {
       this.booking = booking;
       this.busInfo = busInfo;
       this.passenger = passenger;
       this.seatNo = seatNo;
       this.bookDate = bookDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="book_seat_id", unique=true, nullable=false)
    public Integer getBookSeatId() {
        return this.bookSeatId;
    }
    
    public void setBookSeatId(Integer bookSeatId) {
        this.bookSeatId = bookSeatId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="book_id")
    public Booking getBooking() {
        return this.booking;
    }
    
    public void setBooking(Booking booking) {
        this.booking = booking;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bus_id")
    public BusInfo getBusInfo() {
        return this.busInfo;
    }
    
    public void setBusInfo(BusInfo busInfo) {
        this.busInfo = busInfo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pass_id")
    public Passenger getPassenger() {
        return this.passenger;
    }
    
    public void setPassenger(Passenger passenger) {
        this.passenger = passenger;
    }

    
    @Column(name="seat_no", length=45)
    public String getSeatNo() {
        return this.seatNo;
    }
    
    public void setSeatNo(String seatNo) {
        this.seatNo = seatNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="book_date", length=10)
    public Date getBookDate() {
        return this.bookDate;
    }
    
    public void setBookDate(Date bookDate) {
        this.bookDate = bookDate;
    }




}


