package com.mycompany.bus_management.domain;
// Generated Jul 25, 2018 2:36:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BusInfo generated by hbm2java
 */
@Entity
@Table(name="bus_info"
    ,catalog="bus_management"
)
public class BusInfo  implements java.io.Serializable {


     private Integer busId;
     private Integer busNo;
     private String busRegNo;
     private String busModel;
     private Integer busCapacity;
     private Date purchaseDate;
     private String insuranceStatus;
     private Date insuranceDate;
     private String insuranceExpiry;
     private String busType;
     private String busPhoto;
     private Set<BusSchedule> busSchedules = new HashSet<BusSchedule>(0);
     private Set<BookingSeat> bookingSeats = new HashSet<BookingSeat>(0);
     private Set<Route> routes = new HashSet<Route>(0);
     private Set<Booking> bookings = new HashSet<Booking>(0);
     private Set<SaleAccount> saleAccounts = new HashSet<SaleAccount>(0);

    public BusInfo() {
    }

    public BusInfo(Integer busNo, String busRegNo, String busModel, Integer busCapacity, Date purchaseDate, String insuranceStatus, Date insuranceDate, String insuranceExpiry, String busType, String busPhoto, Set<BusSchedule> busSchedules, Set<BookingSeat> bookingSeats, Set<Route> routes, Set<Booking> bookings, Set<SaleAccount> saleAccounts) {
       this.busNo = busNo;
       this.busRegNo = busRegNo;
       this.busModel = busModel;
       this.busCapacity = busCapacity;
       this.purchaseDate = purchaseDate;
       this.insuranceStatus = insuranceStatus;
       this.insuranceDate = insuranceDate;
       this.insuranceExpiry = insuranceExpiry;
       this.busType = busType;
       this.busPhoto = busPhoto;
       this.busSchedules = busSchedules;
       this.bookingSeats = bookingSeats;
       this.routes = routes;
       this.bookings = bookings;
       this.saleAccounts = saleAccounts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="bus_id", unique=true, nullable=false)
    public Integer getBusId() {
        return this.busId;
    }
    
    public void setBusId(Integer busId) {
        this.busId = busId;
    }

    
    @Column(name="bus_no")
    public Integer getBusNo() {
        return this.busNo;
    }
    
    public void setBusNo(Integer busNo) {
        this.busNo = busNo;
    }

    
    @Column(name="bus_reg_no", length=45)
    public String getBusRegNo() {
        return this.busRegNo;
    }
    
    public void setBusRegNo(String busRegNo) {
        this.busRegNo = busRegNo;
    }

    
    @Column(name="bus_model", length=45)
    public String getBusModel() {
        return this.busModel;
    }
    
    public void setBusModel(String busModel) {
        this.busModel = busModel;
    }

    
    @Column(name="bus_capacity")
    public Integer getBusCapacity() {
        return this.busCapacity;
    }
    
    public void setBusCapacity(Integer busCapacity) {
        this.busCapacity = busCapacity;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="purchase_date", length=10)
    public Date getPurchaseDate() {
        return this.purchaseDate;
    }
    
    public void setPurchaseDate(Date purchaseDate) {
        this.purchaseDate = purchaseDate;
    }

    
    @Column(name="insurance_status", length=45)
    public String getInsuranceStatus() {
        return this.insuranceStatus;
    }
    
    public void setInsuranceStatus(String insuranceStatus) {
        this.insuranceStatus = insuranceStatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="insurance_date", length=10)
    public Date getInsuranceDate() {
        return this.insuranceDate;
    }
    
    public void setInsuranceDate(Date insuranceDate) {
        this.insuranceDate = insuranceDate;
    }

    
    @Column(name="insurance_expiry", length=45)
    public String getInsuranceExpiry() {
        return this.insuranceExpiry;
    }
    
    public void setInsuranceExpiry(String insuranceExpiry) {
        this.insuranceExpiry = insuranceExpiry;
    }

    
    @Column(name="bus_type", length=45)
    public String getBusType() {
        return this.busType;
    }
    
    public void setBusType(String busType) {
        this.busType = busType;
    }

    
    @Column(name="bus_photo", length=200)
    public String getBusPhoto() {
        return this.busPhoto;
    }
    
    public void setBusPhoto(String busPhoto) {
        this.busPhoto = busPhoto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="busInfo")
    public Set<BusSchedule> getBusSchedules() {
        return this.busSchedules;
    }
    
    public void setBusSchedules(Set<BusSchedule> busSchedules) {
        this.busSchedules = busSchedules;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="busInfo")
    public Set<BookingSeat> getBookingSeats() {
        return this.bookingSeats;
    }
    
    public void setBookingSeats(Set<BookingSeat> bookingSeats) {
        this.bookingSeats = bookingSeats;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="busInfo")
    public Set<Route> getRoutes() {
        return this.routes;
    }
    
    public void setRoutes(Set<Route> routes) {
        this.routes = routes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="busInfo")
    public Set<Booking> getBookings() {
        return this.bookings;
    }
    
    public void setBookings(Set<Booking> bookings) {
        this.bookings = bookings;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="busInfo")
    public Set<SaleAccount> getSaleAccounts() {
        return this.saleAccounts;
    }
    
    public void setSaleAccounts(Set<SaleAccount> saleAccounts) {
        this.saleAccounts = saleAccounts;
    }




}


