package com.mycompany.bus_management.domain;
// Generated Jul 25, 2018 2:36:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BusSchedule generated by hbm2java
 */
@Entity
@Table(name="bus_schedule"
    ,catalog="bus_management"
)
public class BusSchedule  implements java.io.Serializable {


     private Integer scheduleId;
     private BusInfo busInfo;
     private Employee employee;
     private Route route;
     private Date dateSchdule;
     private String departTime;
     private Integer scheduleStart;
     private String departPlace;
     private Set<SaleAccount> saleAccounts = new HashSet<SaleAccount>(0);
     private Set<Booking> bookings = new HashSet<Booking>(0);

    public BusSchedule() {
    }

    public BusSchedule(BusInfo busInfo, Employee employee, Route route, Date dateSchdule, String departTime, Integer scheduleStart, String departPlace, Set<SaleAccount> saleAccounts, Set<Booking> bookings) {
       this.busInfo = busInfo;
       this.employee = employee;
       this.route = route;
       this.dateSchdule = dateSchdule;
       this.departTime = departTime;
       this.scheduleStart = scheduleStart;
       this.departPlace = departPlace;
       this.saleAccounts = saleAccounts;
       this.bookings = bookings;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="schedule_id", unique=true, nullable=false)
    public Integer getScheduleId() {
        return this.scheduleId;
    }
    
    public void setScheduleId(Integer scheduleId) {
        this.scheduleId = scheduleId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bus_id")
    public BusInfo getBusInfo() {
        return this.busInfo;
    }
    
    public void setBusInfo(BusInfo busInfo) {
        this.busInfo = busInfo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emp_id")
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="route_id")
    public Route getRoute() {
        return this.route;
    }
    
    public void setRoute(Route route) {
        this.route = route;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_schdule", length=10)
    public Date getDateSchdule() {
        return this.dateSchdule;
    }
    
    public void setDateSchdule(Date dateSchdule) {
        this.dateSchdule = dateSchdule;
    }

    
    @Column(name="depart_time", length=45)
    public String getDepartTime() {
        return this.departTime;
    }
    
    public void setDepartTime(String departTime) {
        this.departTime = departTime;
    }

    
    @Column(name="schedule_start")
    public Integer getScheduleStart() {
        return this.scheduleStart;
    }
    
    public void setScheduleStart(Integer scheduleStart) {
        this.scheduleStart = scheduleStart;
    }

    
    @Column(name="depart_place", length=45)
    public String getDepartPlace() {
        return this.departPlace;
    }
    
    public void setDepartPlace(String departPlace) {
        this.departPlace = departPlace;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="busSchedule")
    public Set<SaleAccount> getSaleAccounts() {
        return this.saleAccounts;
    }
    
    public void setSaleAccounts(Set<SaleAccount> saleAccounts) {
        this.saleAccounts = saleAccounts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="busSchedule")
    public Set<Booking> getBookings() {
        return this.bookings;
    }
    
    public void setBookings(Set<Booking> bookings) {
        this.bookings = bookings;
    }




}


