package com.mycompany.bus_management.domain;
// Generated Jul 25, 2018 2:36:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name="employee"
    ,catalog="bus_management"
)
public class Employee  implements java.io.Serializable {


     private Integer empId;
     private EmpCategory empCategory;
     private String empName;
     private String gender;
     private Date dob;
     private String moblic;
     private String address;
     private Date resignedDate;
     private String empPhoto;
     private Set<BusSchedule> busSchedules = new HashSet<BusSchedule>(0);
     private Set<Route> routes = new HashSet<Route>(0);
     private Set<Salary> salaries = new HashSet<Salary>(0);

    public Employee() {
    }

    public Employee(EmpCategory empCategory, String empName, String gender, Date dob, String moblic, String address, Date resignedDate, String empPhoto, Set<BusSchedule> busSchedules, Set<Route> routes, Set<Salary> salaries) {
       this.empCategory = empCategory;
       this.empName = empName;
       this.gender = gender;
       this.dob = dob;
       this.moblic = moblic;
       this.address = address;
       this.resignedDate = resignedDate;
       this.empPhoto = empPhoto;
       this.busSchedules = busSchedules;
       this.routes = routes;
       this.salaries = salaries;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="emp_id", unique=true, nullable=false)
    public Integer getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emp_cat_id")
    public EmpCategory getEmpCategory() {
        return this.empCategory;
    }
    
    public void setEmpCategory(EmpCategory empCategory) {
        this.empCategory = empCategory;
    }

    
    @Column(name="emp_name", length=45)
    public String getEmpName() {
        return this.empName;
    }
    
    public void setEmpName(String empName) {
        this.empName = empName;
    }

    
    @Column(name="gender", length=45)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dob", length=10)
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }

    
    @Column(name="moblic", length=45)
    public String getMoblic() {
        return this.moblic;
    }
    
    public void setMoblic(String moblic) {
        this.moblic = moblic;
    }

    
    @Column(name="address", length=45)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="resigned_date", length=10)
    public Date getResignedDate() {
        return this.resignedDate;
    }
    
    public void setResignedDate(Date resignedDate) {
        this.resignedDate = resignedDate;
    }

    
    @Column(name="emp_photo", length=200)
    public String getEmpPhoto() {
        return this.empPhoto;
    }
    
    public void setEmpPhoto(String empPhoto) {
        this.empPhoto = empPhoto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="employee")
    public Set<BusSchedule> getBusSchedules() {
        return this.busSchedules;
    }
    
    public void setBusSchedules(Set<BusSchedule> busSchedules) {
        this.busSchedules = busSchedules;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="employee")
    public Set<Route> getRoutes() {
        return this.routes;
    }
    
    public void setRoutes(Set<Route> routes) {
        this.routes = routes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="employee")
    public Set<Salary> getSalaries() {
        return this.salaries;
    }
    
    public void setSalaries(Set<Salary> salaries) {
        this.salaries = salaries;
    }




}


