package com.mycompany.bus_management.domain;
// Generated Jul 25, 2018 2:36:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Passenger generated by hbm2java
 */
@Entity
@Table(name="passenger"
    ,catalog="bus_management"
)
public class Passenger  implements java.io.Serializable {


     private Integer passId;
     private String passName;
     private String passAddress;
     private String passMobile;
     private Date regDate;
     private String email;
     private String passPhoto;
     private String gender;
     private Set<Payment> payments = new HashSet<Payment>(0);
     private Set<Booking> bookings = new HashSet<Booking>(0);
     private Set<BookingSeat> bookingSeats = new HashSet<BookingSeat>(0);

    public Passenger() {
    }

    public Passenger(String passName, String passAddress, String passMobile, Date regDate, String email, String passPhoto, String gender, Set<Payment> payments, Set<Booking> bookings, Set<BookingSeat> bookingSeats) {
       this.passName = passName;
       this.passAddress = passAddress;
       this.passMobile = passMobile;
       this.regDate = regDate;
       this.email = email;
       this.passPhoto = passPhoto;
       this.gender = gender;
       this.payments = payments;
       this.bookings = bookings;
       this.bookingSeats = bookingSeats;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="pass_id", unique=true, nullable=false)
    public Integer getPassId() {
        return this.passId;
    }
    
    public void setPassId(Integer passId) {
        this.passId = passId;
    }

    
    @Column(name="pass_name", length=45)
    public String getPassName() {
        return this.passName;
    }
    
    public void setPassName(String passName) {
        this.passName = passName;
    }

    
    @Column(name="pass_address", length=100)
    public String getPassAddress() {
        return this.passAddress;
    }
    
    public void setPassAddress(String passAddress) {
        this.passAddress = passAddress;
    }

    
    @Column(name="pass_mobile", length=45)
    public String getPassMobile() {
        return this.passMobile;
    }
    
    public void setPassMobile(String passMobile) {
        this.passMobile = passMobile;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="reg_date", length=10)
    public Date getRegDate() {
        return this.regDate;
    }
    
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="pass_photo", length=200)
    public String getPassPhoto() {
        return this.passPhoto;
    }
    
    public void setPassPhoto(String passPhoto) {
        this.passPhoto = passPhoto;
    }

    
    @Column(name="gender", length=45)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="passenger")
    public Set<Payment> getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set<Payment> payments) {
        this.payments = payments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="passenger")
    public Set<Booking> getBookings() {
        return this.bookings;
    }
    
    public void setBookings(Set<Booking> bookings) {
        this.bookings = bookings;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="passenger")
    public Set<BookingSeat> getBookingSeats() {
        return this.bookingSeats;
    }
    
    public void setBookingSeats(Set<BookingSeat> bookingSeats) {
        this.bookingSeats = bookingSeats;
    }




}


