package com.mycompany.bus_management.domain;
// Generated Jul 25, 2018 2:36:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name="payment"
    ,catalog="bus_management"
)
public class Payment  implements java.io.Serializable {


     private Integer payId;
     private Passenger passenger;
     private Date payDate;
     private Double priceOfTicket;
     private Integer numberOfTicket;
     private Double totalFair;
     private Integer transcationId;

    public Payment() {
    }

    public Payment(Passenger passenger, Date payDate, Double priceOfTicket, Integer numberOfTicket, Double totalFair, Integer transcationId) {
       this.passenger = passenger;
       this.payDate = payDate;
       this.priceOfTicket = priceOfTicket;
       this.numberOfTicket = numberOfTicket;
       this.totalFair = totalFair;
       this.transcationId = transcationId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="pay_id", unique=true, nullable=false)
    public Integer getPayId() {
        return this.payId;
    }
    
    public void setPayId(Integer payId) {
        this.payId = payId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pass_id")
    public Passenger getPassenger() {
        return this.passenger;
    }
    
    public void setPassenger(Passenger passenger) {
        this.passenger = passenger;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="pay_date", length=10)
    public Date getPayDate() {
        return this.payDate;
    }
    
    public void setPayDate(Date payDate) {
        this.payDate = payDate;
    }

    
    @Column(name="price_of_ticket", precision=22, scale=0)
    public Double getPriceOfTicket() {
        return this.priceOfTicket;
    }
    
    public void setPriceOfTicket(Double priceOfTicket) {
        this.priceOfTicket = priceOfTicket;
    }

    
    @Column(name="number_of_ticket")
    public Integer getNumberOfTicket() {
        return this.numberOfTicket;
    }
    
    public void setNumberOfTicket(Integer numberOfTicket) {
        this.numberOfTicket = numberOfTicket;
    }

    
    @Column(name="total_fair", precision=22, scale=0)
    public Double getTotalFair() {
        return this.totalFair;
    }
    
    public void setTotalFair(Double totalFair) {
        this.totalFair = totalFair;
    }

    
    @Column(name="transcation_id")
    public Integer getTranscationId() {
        return this.transcationId;
    }
    
    public void setTranscationId(Integer transcationId) {
        this.transcationId = transcationId;
    }




}


