package com.mycompany.bus_management.domain;
// Generated Jul 25, 2018 2:36:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RouteCounter generated by hbm2java
 */
@Entity
@Table(name="route_counter"
    ,catalog="bus_management"
)
public class RouteCounter  implements java.io.Serializable {


     private int counterId;
     private Route route;
     private String counterName;
     private String counterAddress;
     private String contactNo;
     private Set<Booking> bookings = new HashSet<Booking>(0);

    public RouteCounter() {
    }

	
    public RouteCounter(int counterId) {
        this.counterId = counterId;
    }
    public RouteCounter(int counterId, Route route, String counterName, String counterAddress, String contactNo, Set<Booking> bookings) {
       this.counterId = counterId;
       this.route = route;
       this.counterName = counterName;
       this.counterAddress = counterAddress;
       this.contactNo = contactNo;
       this.bookings = bookings;
    }
   
     @Id 

    
    @Column(name="counter_id", unique=true, nullable=false)
    public int getCounterId() {
        return this.counterId;
    }
    
    public void setCounterId(int counterId) {
        this.counterId = counterId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="route_id")
    public Route getRoute() {
        return this.route;
    }
    
    public void setRoute(Route route) {
        this.route = route;
    }

    
    @Column(name="counter_name", length=45)
    public String getCounterName() {
        return this.counterName;
    }
    
    public void setCounterName(String counterName) {
        this.counterName = counterName;
    }

    
    @Column(name="counter_address", length=45)
    public String getCounterAddress() {
        return this.counterAddress;
    }
    
    public void setCounterAddress(String counterAddress) {
        this.counterAddress = counterAddress;
    }

    
    @Column(name="contact_no", length=45)
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="routeCounter")
    public Set<Booking> getBookings() {
        return this.bookings;
    }
    
    public void setBookings(Set<Booking> bookings) {
        this.bookings = bookings;
    }




}


