package com.mycompany.bus_management.domain;
// Generated Jul 25, 2018 2:36:02 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Salary generated by hbm2java
 */
@Entity
@Table(name="salary"
    ,catalog="bus_management"
)
public class Salary  implements java.io.Serializable {


     private Integer salaryId;
     private EmpCategory empCategory;
     private Employee employee;
     private SalaryType salaryType;
     private double basic;
     private int noOfTrip;
     private double festivalFee;
     private double insuranceFee;
     private double totalSalary;

    public Salary() {
    }

    public Salary(EmpCategory empCategory, Employee employee, SalaryType salaryType, double basic, int noOfTrip, double festivalFee, double insuranceFee, double totalSalary) {
       this.empCategory = empCategory;
       this.employee = employee;
       this.salaryType = salaryType;
       this.basic = basic;
       this.noOfTrip = noOfTrip;
       this.festivalFee = festivalFee;
       this.insuranceFee = insuranceFee;
       this.totalSalary = totalSalary;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="salary_id", unique=true, nullable=false)
    public Integer getSalaryId() {
        return this.salaryId;
    }
    
    public void setSalaryId(Integer salaryId) {
        this.salaryId = salaryId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emp_cat_id", nullable=false)
    public EmpCategory getEmpCategory() {
        return this.empCategory;
    }
    
    public void setEmpCategory(EmpCategory empCategory) {
        this.empCategory = empCategory;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emp_id", nullable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="salary_type_id", nullable=false)
    public SalaryType getSalaryType() {
        return this.salaryType;
    }
    
    public void setSalaryType(SalaryType salaryType) {
        this.salaryType = salaryType;
    }

    
    @Column(name="basic", nullable=false, precision=22, scale=0)
    public double getBasic() {
        return this.basic;
    }
    
    public void setBasic(double basic) {
        this.basic = basic;
    }

    
    @Column(name="no_of_trip", nullable=false)
    public int getNoOfTrip() {
        return this.noOfTrip;
    }
    
    public void setNoOfTrip(int noOfTrip) {
        this.noOfTrip = noOfTrip;
    }

    
    @Column(name="festival_fee", nullable=false, precision=22, scale=0)
    public double getFestivalFee() {
        return this.festivalFee;
    }
    
    public void setFestivalFee(double festivalFee) {
        this.festivalFee = festivalFee;
    }

    
    @Column(name="insurance_fee", nullable=false, precision=22, scale=0)
    public double getInsuranceFee() {
        return this.insuranceFee;
    }
    
    public void setInsuranceFee(double insuranceFee) {
        this.insuranceFee = insuranceFee;
    }

    
    @Column(name="total_salary", nullable=false, precision=22, scale=0)
    public double getTotalSalary() {
        return this.totalSalary;
    }
    
    public void setTotalSalary(double totalSalary) {
        this.totalSalary = totalSalary;
    }




}


