package com.mycompany.bus_management.domain;
// Generated Jul 25, 2018 2:36:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SalaryType generated by hbm2java
 */
@Entity
@Table(name="salary_type"
    ,catalog="bus_management"
)
public class SalaryType  implements java.io.Serializable {


     private Integer salaryTypeId;
     private String salaryType;
     private Set<Salary> salaries = new HashSet<Salary>(0);

    public SalaryType() {
    }

	
    public SalaryType(String salaryType) {
        this.salaryType = salaryType;
    }
    public SalaryType(String salaryType, Set<Salary> salaries) {
       this.salaryType = salaryType;
       this.salaries = salaries;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="salary_type_id", unique=true, nullable=false)
    public Integer getSalaryTypeId() {
        return this.salaryTypeId;
    }
    
    public void setSalaryTypeId(Integer salaryTypeId) {
        this.salaryTypeId = salaryTypeId;
    }

    
    @Column(name="salary_type", nullable=false, length=45)
    public String getSalaryType() {
        return this.salaryType;
    }
    
    public void setSalaryType(String salaryType) {
        this.salaryType = salaryType;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="salaryType")
    public Set<Salary> getSalaries() {
        return this.salaries;
    }
    
    public void setSalaries(Set<Salary> salaries) {
        this.salaries = salaries;
    }




}


