package com.mycompany.bus_management.domain;
// Generated Jul 25, 2018 2:36:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SaleAccount generated by hbm2java
 */
@Entity
@Table(name="sale_account"
    ,catalog="bus_management"
)
public class SaleAccount  implements java.io.Serializable {


     private Integer id;
     private BusInfo busInfo;
     private BusSchedule busSchedule;
     private Route route;
     private Integer amountOfTicket;
     private Double ticketPrice;
     private Double totalPrice;
     private Date saleDate;

    public SaleAccount() {
    }

    public SaleAccount(BusInfo busInfo, BusSchedule busSchedule, Route route, Integer amountOfTicket, Double ticketPrice, Double totalPrice, Date saleDate) {
       this.busInfo = busInfo;
       this.busSchedule = busSchedule;
       this.route = route;
       this.amountOfTicket = amountOfTicket;
       this.ticketPrice = ticketPrice;
       this.totalPrice = totalPrice;
       this.saleDate = saleDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bus_id")
    public BusInfo getBusInfo() {
        return this.busInfo;
    }
    
    public void setBusInfo(BusInfo busInfo) {
        this.busInfo = busInfo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="schedule_id")
    public BusSchedule getBusSchedule() {
        return this.busSchedule;
    }
    
    public void setBusSchedule(BusSchedule busSchedule) {
        this.busSchedule = busSchedule;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="route_id")
    public Route getRoute() {
        return this.route;
    }
    
    public void setRoute(Route route) {
        this.route = route;
    }

    
    @Column(name="amount_of_ticket")
    public Integer getAmountOfTicket() {
        return this.amountOfTicket;
    }
    
    public void setAmountOfTicket(Integer amountOfTicket) {
        this.amountOfTicket = amountOfTicket;
    }

    
    @Column(name="ticket_price", precision=22, scale=0)
    public Double getTicketPrice() {
        return this.ticketPrice;
    }
    
    public void setTicketPrice(Double ticketPrice) {
        this.ticketPrice = ticketPrice;
    }

    
    @Column(name="total_price", precision=22, scale=0)
    public Double getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="sale_date", length=10)
    public Date getSaleDate() {
        return this.saleDate;
    }
    
    public void setSaleDate(Date saleDate) {
        this.saleDate = saleDate;
    }




}


