package com.mycompany.bus_management.domain;
// Generated Jul 25, 2018 2:36:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserType generated by hbm2java
 */
@Entity
@Table(name=" user_type"
    ,catalog="bus_management"
)
public class UserType  implements java.io.Serializable {


     private Integer UTypeId;
     private String UTypeName;
     private Set<User> users = new HashSet<User>(0);

    public UserType() {
    }

    public UserType(String UTypeName, Set<User> users) {
       this.UTypeName = UTypeName;
       this.users = users;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="u_type_id", unique=true, nullable=false)
    public Integer getUTypeId() {
        return this.UTypeId;
    }
    
    public void setUTypeId(Integer UTypeId) {
        this.UTypeId = UTypeId;
    }

    
    @Column(name="u_type_name", length=45)
    public String getUTypeName() {
        return this.UTypeName;
    }
    
    public void setUTypeName(String UTypeName) {
        this.UTypeName = UTypeName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userType")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


