package com.mycompany.bus_management.domain;
// Generated Jul 25, 2018 2:36:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="bus_management"
)
public class User  implements java.io.Serializable {


     private Integer userId;
     private UserType userType;
     private String userName;
     private String userPass;
     private Set<LoginInfo> loginInfos = new HashSet<LoginInfo>(0);

    public User() {
    }

    public User(UserType userType, String userName, String userPass, Set<LoginInfo> loginInfos) {
       this.userType = userType;
       this.userName = userName;
       this.userPass = userPass;
       this.loginInfos = loginInfos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="user_id", unique=true, nullable=false)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="u_type_id")
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }

    
    @Column(name="user_name", length=45)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="user_pass", length=45)
    public String getUserPass() {
        return this.userPass;
    }
    
    public void setUserPass(String userPass) {
        this.userPass = userPass;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<LoginInfo> getLoginInfos() {
        return this.loginInfos;
    }
    
    public void setLoginInfos(Set<LoginInfo> loginInfos) {
        this.loginInfos = loginInfos;
    }




}


